name: Check sources
on: push
jobs:
  testscript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  runtests:
    needs: [shellcheck, testscript]
    name: RunTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: make tests

  doc:
    name: PublishDoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make doc
      - name: Publish Doc
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
